### ISSUE TITLE
Написание документации Максим

### ISSUE THREAD

**Issue by VZaigraev** [VZaigraev/materials-metrology#9]
Проект технического задания
Шаблон методики испытаний

**Comment by Simalep** [comment]
Files "**TZ.docx**" and "**Shablon_metodiki_ispytaniy.docx**" were uploaded on: [link](https://drive.google.com/drive/folders/1Io9FiP2LYpUmahY1xG6uSOWqQ_wqFn7w)

**Comment by Simalep** [comment]
[File](https://drive.google.com/drive/folders/1Io9FiP2LYpUmahY1xG6uSOWqQ_wqFn7w) was updated. 
[ТЗ_2.0.docx](https://github.com/VZaigraev/materials-metrology/files/4398979/_2.0.docx)
